### ISSUE TITLE
Blurry/squished icons on GNOME notifications

### ISSUE THREAD

**Issue by zackelia** [pog102/devify#11]
```
OS Name              Ubuntu 23.04
OS Type              64-bit
GNOME Version        44.0
Windowing System     Wayland
Kernel Version       Linux 6.2.0-23-generic
```
![blurry-icons](https://github.com/pog102/devify/assets/31748637/21ae948e-6dee-4178-9ef4-9221c160f5fb)

Not entirely sure if an issue with the SVGs or a limitation with GNOME/Ubuntu.

**Comment by pog102** [comment]
Did some testing, seems GNOME does only square icon sizes so any icon exceeding the square dimensions becomes distorted. Found a way to fix this by increasing the canvas size to match the square shape.
![image](https://github.com/pog102/devify/assets/85764555/d2188950-04bb-40d2-96bf-0d5a6b85b953)
