### ISSUE TITLE
Duplicate Notifications

### ISSUE THREAD

**Issue by pog102** [pog102/devify#14]
For mouse and keyboard I get duplicate notifications
![image](https://github.com/pog102/devify/assets/85764555/912faa26-420e-4347-9da1-8ad368ffc883)
![image](https://github.com/pog102/devify/assets/85764555/96e854e9-cc98-4d32-99a4-e707830b17aa)
output from udev (mouse):
```
KERNEL[510.249388] add      /devices/pci0000:00/0000:00:15.0/usb1/1-4/1-4:1.0/0003:1B1C:1B94.0006 (hid)
ACTION=add
DEVPATH=/devices/pci0000:00/0000:00:15.0/usb1/1-4/1-4:1.0/0003:1B1C:1B94.0006
SUBSYSTEM=hid
HID_ID=0003:00001B1C:00001B94
HID_NAME=Corsair CORSAIR KATAR PRO Wireless Gaming Dongle
HID_PHYS=usb-0000:00:15.0-4/input0
HID_UNIQ=FB71C1BF4159EC9B
MODALIAS=hid:b0003g0001v00001B1Cp00001B94
SEQNUM=3453
...
KERNEL[510.250372] add      /devices/pci0000:00/0000:00:15.0/usb1/1-4/1-4:1.1/0003:1B1C:1B94.0007 (hid)
ACTION=add
DEVPATH=/devices/pci0000:00/0000:00:15.0/usb1/1-4/1-4:1.1/0003:1B1C:1B94.0007
SUBSYSTEM=hid
HID_ID=0003:00001B1C:00001B94
HID_NAME=Corsair CORSAIR KATAR PRO Wireless Gaming Dongle
HID_PHYS=usb-0000:00:15.0-4/input1
HID_UNIQ=FB71C1BF4159EC9B
MODALIAS=hid:b0003g0001v00001B1Cp00001B94
SEQNUM=3462
...
KERNEL[510.251002] add      /devices/pci0000:00/0000:00:15.0/usb1/1-4/1-4:1.2/0003:1B1C:1B94.0008 (hid)
ACTION=add
DEVPATH=/devices/pci0000:00/0000:00:15.0/usb1/1-4/1-4:1.2/0003:1B1C:1B94.0008
SUBSYSTEM=hid
HID_ID=0003:00001B1C:00001B94
HID_NAME=Corsair CORSAIR KATAR PRO Wireless Gaming Dongle
HID_PHYS=usb-0000:00:15.0-4/input2
HID_UNIQ=FB71C1BF4159EC9B
MODALIAS=hid:b0003g0001v00001B1Cp00001B94
SEQNUM=3469

```

**Comment by lima-limon-inc** [comment]
I only have the repeated notification with a some devices (for instance my webcam and keyboard)
My mouse is fine.
Weird...

**Comment by pog102** [comment]
I'm thinking of adding the -r flag to notify-send, idk if there're any better solutions to this.

**Comment by luisbocanegra** [comment]
Can you try #22 ? It seems to solve the duplicated notifications for my mouse but can't test with other input devices
**Note** It sets a random string before the title so Plasma doesn't silently mute them for me, this is only temporary

If it works please do not merge yet, I'll do some cleanup before

**Comment by pog102** [comment]
Works great. Keep up the good work!
